default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ifood_development
  username: postgres
  password: postgres
  
test:
  <<: *default
  database: ifood_test
  username: postgres
  password: postgres
production:
  <<: *default
  database: ifood_production
  username: ifood
  password: <%= ENV['IFOOD_DATABASE_PASSWORD'] %>
